local builtin = require('telescope.builtin')
local themes = require('telescope.themes')
vim.keymap.set('n', '<leader>pf', function()
    builtin.find_files(themes.get_ivy({}))
end,{})
vim.keymap.set('n', '<leader><C-p>', builtin.git_files)
vim.keymap.set('n', '<leader>pg', function()
    builtin.resume(themes.get_ivy({}))
end, {})
